import 'package:flutter/widgets.dart';

import 'app_localizations.dart';

/// Stable compatibility wrapper so code can use `L10n` even when
/// `app_localizations.dart` is regenerated by `flutter gen-l10n`.
class L10n {
  static AppLocalizations? of(BuildContext context) =>
      AppLocalizations.of(context);
  static LocalizationsDelegate<AppLocalizations> get delegate =>
      AppLocalizations.delegate;
  static List<LocalizationsDelegate<dynamic>> get localizationsDelegates =>
      AppLocalizations.localizationsDelegates;
  static List<Locale> get supportedLocales => AppLocalizations.supportedLocales;
}
