// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczBH1EjcxC5DK6W9v4dwjLnrW0KaAeTg',
    appId: '1:937930146429:web:5f50e64e14dc19913fe714',
    messagingSenderId: '937930146429',
    projectId: 'assistant-434717',
    authDomain: 'assistant-434717.firebaseapp.com',
    storageBucket: 'assistant-434717.firebasestorage.app',
    measurementId: 'G-G6933TC69G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMxeFR3KK385QnKRCCgg3u7YEX9FIofWg',
    appId: '1:937930146429:android:0523280c28d960923fe714',
    messagingSenderId: '937930146429',
    projectId: 'assistant-434717',
    storageBucket: 'assistant-434717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA295HZ1bg4_S9nJLzb1sFl1IH8jRWfgx8',
    appId: '1:937930146429:ios:29aaba15d90e0f9d3fe714',
    messagingSenderId: '937930146429',
    projectId: 'assistant-434717',
    storageBucket: 'assistant-434717.firebasestorage.app',
    iosBundleId: 'com.example.filmflix',
  );
}
